### ISSUE TITLE
0086 | காந்தி யார்?, காந்தியும் ஜவஹரும், காந்தியும் விவேகானந்தரும் | வாழ்க்கை வரலாறு | வெ. சாமிநாத சர்மா

### ISSUE THREAD

**Issue by tshrinivasan** [KaniyamFoundation/thamizhmann_pathippagam_books#86]

**Comment by gurulenin** [comment]
![086](https://user-images.githubusercontent.com/15311390/63212455-88390d80-c122-11e9-9d7c-66da03619088.jpg)

**Comment by gurulenin** [comment]
![086](https://user-images.githubusercontent.com/15311390/71899118-1456da80-3181-11ea-8491-7b6e348f5d8e.jpg)
![86-2](https://user-images.githubusercontent.com/15311390/71899129-191b8e80-3181-11ea-85ad-4e9bab591880.jpg)
![86-1](https://user-images.githubusercontent.com/15311390/71899130-191b8e80-3181-11ea-972c-90acdc095325.jpg)

**Comment by tshrinivasan** [comment]
splited the books
